### ISSUE TITLE
Errors occuring when run

### ISSUE THREAD

**Issue by 24harter** [TravisLedo/LidarScanRender#4]
Here is the error message that I have every time I set it to run, however no error appears when I hit build/build and clean. 
![image](https://github.com/TravisLedo/LidarScanRender/assets/117326283/97ea761b-a7e6-444b-a1ee-d10c1cf558fd)

**Comment by TravisLedo** [comment]
> 

Hey there, it looks like you are missing JavaFX library. That library is pretty confusing and is constantly changing. I would make sure you install it first, specifically for your IDE.

**Comment by 24harter** [comment]
This is the library I have installed with the jar files in it:
![image](https://github.com/TravisLedo/LidarScanRender/assets/117326283/e6f0fe4e-397d-458a-9fa1-f78013e9a289) The IDE is the latest installment of Netbeans
With this I get the error above. Am I missing something or a different kind of error, I'm new to java so sorry if this seems like a stupid question.
Also, thanks for responding to my issue quickly, I really appreciate it.

**Comment by TravisLedo** [comment]
> This is the library I have installed with the jar files in it: ![image](https://user-images.githubusercontent.com/117326283/254720564-e6f0fe4e-397d-458a-9fa1-f78013e9a289.png) The IDE is the latest installment of Netbeans With this I get the error above. Am I missing something or a different kind of error, I'm new to java so sorry if this seems like a stupid question. Also, thanks for responding to my issue quickly, I really appreciate it.

Hey no worries. I just updated the project to use Gradle. This will auto download all the libraries you need. I also changed to using IntelliJ so please download the free community edition and run instead of Netbeans. It is a much better IDE overall anyway IMO. Let me know how it goes.

**Comment by 24harter** [comment]
I've switched over to IntelliJ and transferred all the files, however I'm currently stuck on trying to run it since figure out what configuration I need.

**Comment by TravisLedo** [comment]
> I've switched over to IntelliJ and transferred all the files, however I'm currently stuck on trying to run it since figure out what configuration I need.

Make sure you delete all the files you had before and just download the whole project again, dont just migrate the old ones into IntelliJ. Then open the project folder from IntelliJ (Not the main LidarScanRender folder but the sub one inside). Once it finishes loading, right click on the App file and select Run. Tell me what errors you get.

**Comment by 24harter** [comment]
I have successfully ran the app, but when I connect it to the com port and hit scan, it doesn't seem to be working. The arduino has the code on it, but seems inactive when I click scan. None of the servos are moving and nothing is appearing on the app or intellij.
Update: I had a basic mistake with the servos and I forgot to ground and power them, but after doing so they just lock in one place and don't move.

**Comment by TravisLedo** [comment]
> I have successfully ran the app, but when I connect it to the com port and hit scan, it doesn't seem to be working. The arduino has the code on it, but seems inactive when I click scan. None of the servos are moving and nothing is appearing on the app or intellij. Update: I had a basic mistake with the servos and I forgot to ground and power them, but after doing so they just lock in one place and don't move.

At this point I think you should test your servos and lidar sensor first before trying to run the whole app. First check to see if you are even getting a reading from the lidar sensor. The servo won't move until the reading at that point is done and if it's getting no reading then it won't move to the next point. Next try to test your servos with test scripts. Get the basics working first. You might even have bad servos. Print everything everywhere to your Arduino monitor as you test so you can know what the code is currently doing.

**Comment by 24harter** [comment]
I have checked my lidar sensor and servos and both were fine. I believe the issue is that my lidar sensor is a tf luna instead of a tf mini-s, as it was mislabelled

**Comment by TravisLedo** [comment]
> I have checked my lidar sensor and servos and both were fine. I believe the issue is that my lidar sensor is a tf luna instead of a tf mini-s, as it was mislabelled

Ah gotcha. Just need to refactor the Arduino code to use your specific sensor's library instead of the one I am using. It should still work, but that will be beyond what I can help you with since I don't own that sensor (I don't even have the one I used on this project anymore either).. Maybe play around with the current sensor you have and see if you can get it working. The fun part any project is making it work for your needs and learning along the way.
